version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rubocop-rails"
      - dependency-name: "rubocop"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "rubocop-rails"
      - dependency-name: "rubocop"
