servers:
  web:
    hosts:
      - 44.196.164.25
    labels:
      traefik.http.routers.micarrera-web-staging.rule: Host(`staging.micarrera.uy`)
      traefik.http.routers.micarrera_secure-web-staging.entrypoints: websecure
      traefik.http.routers.micarrera_secure-web-staging.rule: Host(`staging.micarrera.uy`)
      traefik.http.routers.micarrera_secure-web-staging.tls: true
      traefik.http.routers.micarrera_secure-web-staging.tls.certresolver: letsencrypt
