servers:
  web:
    hosts:
      - 44.196.164.25
    labels:
      traefik.http.routers.micarrera-web-production.rule: Host(`micarrera.uy`)
      traefik.http.routers.micarrera_secure-web-production.entrypoints: websecure
      traefik.http.routers.micarrera_secure-web-production.rule: Host(`micarrera.uy`)
      traefik.http.routers.micarrera_secure-web-production.tls: true
      traefik.http.routers.micarrera_secure-web-production.tls.certresolver: letsencrypt

accessories:
  db_prod:
    image: postgres:15.4
    host: 54.145.40.246
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'mi_carrera'
        POSTGRES_DB: 'mi_carrera_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
