name: Scraper
on:
  push:
    branches:
      - 'gh-action-scraper'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Update libyaml to 0.2.5
      run: |
          wget http://mirrors.kernel.org/ubuntu/pool/main/liby/libyaml/libyaml-0-2_0.2.5-1_amd64.deb
          sudo apt-get install ./libyaml-0-2_0.2.5-1_amd64.deb
    - name: Run scraper
      run: |
          bundle exec rake scraper
    - name: Setup git config
      run: |
          git config --global user.email "micarrera@cedarcode.com"
          git config --global user.name "MiCarrera"
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
          git add db/data
          CHANGED_FILES=$(git status --porcelain | grep -v '^??')
          if [ -n "$CHANGED_FILES" ]; then
            git commit -m 'Update db/data from scraper'
            git push -f origin HEAD:scraper
            gh pr create --title "Scraper Updates" --body "Updates from scraper" --head scraper
          else
            echo "No changes detected"
          fi
